title: How to use GitHub pages
author: Inga Ulusoy
email: inga.ulusoy@uni-heidelberg.de
description: > # this means to ignore newlines until "baseurl:"
  We like to test out the learning lab.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  iulusoy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate